### ISSUE TITLE
Problems following Readme.md

### ISSUE THREAD

**Issue by Pelirrojo** [juanpablohp33/D3SpringBoot#1]
Hi!

I'm trying to start your app but I couldn't with the supplied documentation in README.md file. In these kind if files, usually I would expect to find something like:

* Tools and programming language specific version i.e. Java 8, MySQL 5.3,...
* Steps to compile and start the code:
i.e. 
````bash
      # cd backend
      # mvn compile
````
* Urls locally access test your app 
   * **backend** localhost:8080/resource
   * **frontend** localost:4200/home/file.html
*  And some documentation about the data processes followed.

Could you help me please?

Thanks in advance,
Manuel

**Comment by juanpablohp33** [comment]
Hi, 

Thank for read our article, We chang Readme and there is a INFORME in wiki.

Thanks alot.
